---
title: "GO analysis"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(clusterProfiler)
library(org.Hs.eg.db)
library(enrichplot)
library(ggplot2)

```

```{r}
# Helper function for GO analysis and dotplot visualization
perform_go_analysis <- function(gene_list, label) {
  if (length(gene_list) < 3) {
    message("Too few genes (", length(gene_list), ") for GO BP analysis in '", label, "'. Skipping.")
    return(NULL)
  }
  
  ego <- tryCatch(
    {
      enrichGO(gene          = gene_list,
               OrgDb         = org.Hs.eg.db,
               keyType       = "ENSEMBL",
               ont           = "BP",
               pAdjustMethod = "BH",
               pvalueCutoff  = 0.05,
               qvalueCutoff  = 0.2)
    },
    error = function(e) {
      message("Error in enrichGO for '", label, "': ", e$message)
      return(NULL)
    }
  )
  
  if (is.null(ego) || nrow(as.data.frame(ego)) == 0) {
    message("No significant GO BP results for '", label, "'.")
    return(NULL)
  }
  
  message("Found ", nrow(as.data.frame(ego)), " GO BP categories for '", label, "'.")
    
  
  # Create dotplot
  p <- dotplot(ego, showCategory=10) +
    ggtitle(paste("GO BP:", label))
  
  print(p)
  
  # Save the plot
  filename <- paste0("../figures/GO_BP_", gsub(" ", "_", label), ".png")
  ggsave(filename, plot = p, width = 10, height = 6, dpi = 300)
  message("Saved plot as: ", filename)
  
  return(ego)
}
```



```{r}
# Perform GO analysis for unique genes in each supercluster
message("GO BP enrichment analysis for unique genes in 'Amygdala excitatory'")
ego_Amygdala <- perform_go_analysis(unique_Amygdala, "Amygdala excitatory")

message("GO BP enrichment analysis for unique genes in 'Hippocampal CA1-3'")
ego_Hippocampal <- perform_go_analysis(unique_Hippocampal, "Hippocampal CA1-3")
ye
message("GO BP enrichment analysis for common genes")
ego_Common <- perform_go_analysis(common_genes, "Common genes for both superclusters")

```

