---
title: 'T-sne educational attainment'
output: html_document
date: "2025-06-12"
---
# fig_3a_educational_attainment.Rmd
# analogic as fig3a.R but for educational attainment
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(data.table)
library(tidyverse)
library(loomR)
library(here)
library(ggplot2)
library(readxl)

```

```{r}
# 1. LOOM
lfile <- connect(filename = "../data/adult_human_20221007.loom", mode = "r", skip.validate = TRUE)
CellID <- lfile[["col_attrs/CellID"]][]
Cluster <- lfile[["col_attrs/Clusters"]][]
dat <- cbind(CellID, Cluster) %>% as.data.frame()

```

```{r}
# 2. CLuster annotation
CT_annot <- read_excel("../data/silleti_table_s2.xlsx") %>%
  filter(!is.na(Cluster)) %>%
  mutate(Cluster = as.character(Cluster),
         Supercluster = gsub("-| ", "_", Supercluster)) %>%
  dplyr::select(Cluster, Supercluster)

dat <- dat %>%
  mutate(Cluster = as.character(Cluster)) %>%
  left_join(CT_annot, by = "Cluster")

# 3. t-SNEcoordinates
dat.tsne <- fread(here("data/neuron_tsne.csv.gz"))
dat <- dat %>% inner_join(dat.tsne, by = "CellID")
```
```{r}

# 4. data S-LDSC – EDUCATIONAL_ATTAINMENT
dat.cluster.res <- read_xlsx(("../data/Supplementary_Datasets.xlsx"), sheet = "Supplementary_Data_8") %>%
  filter(Phenotype == "educational_attainment") %>%
  separate(Cluster, into = c("V1", "Cluster0"), sep = " \\(", remove = FALSE) %>%
  mutate(Cluster0 = gsub("\\)", "", Cluster0),
         minuslog10P = -log10(P)) %>%
  dplyr::select(Cluster0, minuslog10P, if.sig.fdr)

mylab <- dat %>%
  group_by(Supercluster) %>%
  summarise(TSNE1 = mean(TSNE1), TSNE2 = mean(TSNE2)) %>%
  ungroup()


dat1 <- dat %>%
  left_join(dat.cluster.res, by = c("Cluster" = "Cluster0")) %>%
  mutate(minuslog10P = ifelse(if.sig.fdr == "yes", minuslog10P, NA))
```

```{r}
# 5. plot
p_edu <- ggplot(dat1 %>% mutate(tmp = "not sig. (FDR)"),
                  aes(x = TSNE1, y = TSNE2, color = minuslog10P, fill = tmp)) +
  geom_point(alpha = .1, size = .1) +
  theme_classic() +
  scico::scale_color_scico(palette = "lajolla",
                           direction = -1,
                           na.value = "#E5E5E5", midpoint = 5,
                           name = "educational attainment\n-log10(P)") +
  xlab("tSNE1") + ylab("tSNE2") +
  scale_fill_manual(values = NA, name = "") +
  guides(fill = guide_legend(override.aes = list(fill = "#E5E5E5", size = 2))) +
  annotate(geom = "text", x = mylab$TSNE1, y = mylab$TSNE2, label = mylab$Supercluster,
           color = "black") +
  theme(legend.position = "bottom", legend.box = "horizontal")

# 6. Save
ggsave(p_edu,
       filename = ("../figures/3a_tSNE_educational_attainment.pdf"),
       width = 10, height = 10.5)

```

